plugins {
    id 'java'
    id 'idea'
    id 'org.beryx.runtime' version '1.12.4'
    id 'org.openjfx.javafxplugin' version '0.0.10'
}

idea {
    module {
        inheritOutputDirs = true
    }
}

java {
    modularity.inferModulePath = true
}

group 'com.derpderphurr'
version '0.1.1'

targetCompatibility = JavaVersion.VERSION_17
sourceCompatibility = JavaVersion.VERSION_17

mainClassName = "com.derpderphurr.network.fabric.ui.Launcher"

runtime {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages','--bind-services']
    modules = [
            'java.desktop',
            'java.xml',
            'java.logging',
            'java.sql',
            'java.naming',
            'java.compiler',
            'java.scripting',
            'java.management',
            'java.datatransfer',
            'java.security.sasl',
            'jdk.unsupported',
            'jdk.jfr']
}

javafx {
    modules = [ 'javafx.controls','javafx.swing', 'javafx.fxml' ]
}

repositories {
    mavenCentral()
}

dependencies {
    // Source: https://mvnrepository.com/artifact/tools.jackson.core/jackson-databind
    implementation("tools.jackson.core:jackson-databind:3.2.3")
    implementation("com.fasterxml.jackson.core:jackson-databind:3.2.3")

}

test {
    useJUnitPlatform()
}