package com.derpderphurr.network.fabric;

import org.snmp4j.PDU;
import org.snmp4j.Snmp;
import org.snmp4j.Target;
import org.snmp4j.mp.SnmpConstants;
import org.snmp4j.smi.*;
import org.snmp4j.util.DefaultPDUFactory;
import org.snmp4j.util.TableEvent;
import org.snmp4j.util.TableUtils;

import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.nio.charset.StandardCharsets;
import java.util.*;

/** Generated by Claude **/

/**
 * Stateless, thread-safe LLDP neighbor discovery using only the standard
 * IEEE 802.1AB LLDP-MIB (1.0.8802.1.1.2) plus IF-MIB.
 *
 * One instance can be shared across the application; every call receives its own
 * Snmp session and Target, and no per-call state is stored on the instance.
 *
 * Written against SNMP4J 3.x (generic Target). For 2.x, drop the generics.
 */
public final class LldpNeighborDiscovery {

    // ---- OID definitions (built from int[] so no string parsing) ---------------------

    // lldpObjects = 1.0.8802.1.1.2.1
    private static final int[] LLDP_OBJECTS = {1, 0, 8802, 1, 1, 2, 1};
    private static final int[] LOC_PORT_ENTRY     = concat(LLDP_OBJECTS, 3, 7, 1); // lldpLocPortEntry
    private static final int[] REM_ENTRY          = concat(LLDP_OBJECTS, 4, 1, 1); // lldpRemEntry
    private static final int[] REM_MAN_ADDR_ENTRY = concat(LLDP_OBJECTS, 4, 2, 1); // lldpRemManAddrEntry
    private static final int[] IF_ENTRY   = {1, 3, 6, 1, 2, 1, 2, 2, 1};           // ifEntry
    private static final int[] IFX_ENTRY  = {1, 3, 6, 1, 2, 1, 31, 1, 1, 1};       // ifXEntry

    // lldpLocPortTable (index: lldpLocPortNum)
    private static final OID LOC_PORT_ID_SUBTYPE = new OID(LOC_PORT_ENTRY, 2);
    private static final OID LOC_PORT_ID         = new OID(LOC_PORT_ENTRY, 3);
    private static final OID LOC_PORT_DESC       = new OID(LOC_PORT_ENTRY, 4);

    // lldpRemTable (index: lldpRemTimeMark.lldpRemLocalPortNum.lldpRemIndex)
    private static final OID REM_CHASSIS_SUBTYPE = new OID(REM_ENTRY, 4);
    private static final OID REM_CHASSIS_ID      = new OID(REM_ENTRY, 5);
    private static final OID REM_PORT_SUBTYPE    = new OID(REM_ENTRY, 6);
    private static final OID REM_PORT_ID         = new OID(REM_ENTRY, 7);
    private static final OID REM_PORT_DESC       = new OID(REM_ENTRY, 8);
    private static final OID REM_SYS_NAME        = new OID(REM_ENTRY, 9);
    private static final OID REM_SYS_DESC        = new OID(REM_ENTRY, 10);
    private static final OID REM_CAP_SUPPORTED   = new OID(REM_ENTRY, 11);
    private static final OID REM_CAP_ENABLED     = new OID(REM_ENTRY, 12);

    // lldpRemManAddrTable - the address itself lives in the INDEX
    // index: timeMark.localPortNum.remIndex.addrSubtype.len.addrBytes...
    private static final OID REM_MAN_ADDR_IF_SUBTYPE = new OID(REM_MAN_ADDR_ENTRY, 3);

    // IF-MIB
    private static final OID IF_DESCR = new OID(IF_ENTRY, 2);
    private static final OID IF_NAME  = new OID(IFX_ENTRY, 1);
    private static final OID IF_ALIAS = new OID(IFX_ENTRY, 18);

    // Column sets (arrays are never exposed, so they can't be mutated by callers)
    private static final OID[] LOC_PORT_COLUMNS = {LOC_PORT_ID_SUBTYPE, LOC_PORT_ID, LOC_PORT_DESC};
    private static final OID[] REM_COLUMNS = {REM_CHASSIS_SUBTYPE, REM_CHASSIS_ID, REM_PORT_SUBTYPE,
            REM_PORT_ID, REM_PORT_DESC, REM_SYS_NAME, REM_SYS_DESC, REM_CAP_SUPPORTED, REM_CAP_ENABLED};

    private static final String[] CHASSIS_SUBTYPES = {"?", "chassisComponent", "interfaceAlias",
            "portComponent", "macAddress", "networkAddress", "interfaceName", "local"};
    private static final String[] PORT_SUBTYPES = {"?", "interfaceAlias", "portComponent",
            "macAddress", "networkAddress", "interfaceName", "agentCircuitId", "local"};
    private static final String[] CAPABILITIES = {"other", "repeater", "bridge", "wlanAccessPoint",
            "router", "telephone", "docsisCableDevice", "stationOnly"};

    // ---- Result type ----------------------------------------------------------------



    // ---- Configuration (immutable, so the shared instance is thread-safe) -------------

    private final int maxRowsPerPdu;

    public LldpNeighborDiscovery() {
        this(10);
    }

    /** @param maxRowsPerPdu rows requested per GETBULK; lower it for devices that choke on large responses */
    public LldpNeighborDiscovery(int maxRowsPerPdu) {
        if (maxRowsPerPdu < 1) throw new IllegalArgumentException("maxRowsPerPdu must be >= 1");
        this.maxRowsPerPdu = maxRowsPerPdu;
    }

    // ---- Public API -------------------------------------------------------------------

    /**
     * Discover LLDP neighbors on the given target.
     *
     * @param snmp   an open (listening) Snmp session; not closed by this method
     * @param target the device to query
     * @return neighbors, empty if LLDP is unsupported, disabled, or not in the SNMP view
     * @throws IOException on SNMP timeout or transport failure
     */
    public List<LLDPNeighbor> discover(Snmp snmp, Target<?> target) throws IOException {
        Objects.requireNonNull(snmp, "snmp");
        Objects.requireNonNull(target, "target");

        // Per-call walker: TableUtils holds session/target-specific state, so never share it.
        Walker w = new Walker(snmp, target, maxRowsPerPdu);

        // 1. Local port table: lldpLocPortNum -> local port info
        Map<Integer, LocalPort> locPorts = new HashMap<>();
        for (TableEvent e : w.table(LOC_PORT_COLUMNS)) {
            VariableBinding[] c = e.getColumns();
            locPorts.put(e.getIndex().get(0),
                    new LocalPort(intOf(c[0]), text(octets(c[1])), text(octets(c[2]))));
        }

        // 2. IF-MIB names for mapping LLDP port numbers to ifIndex
        Interfaces ifs = new Interfaces(w.column(IF_NAME), w.column(IF_DESCR), w.column(IF_ALIAS));

        // 3. Remote table
        Map<String, Builder> byKey = new LinkedHashMap<>();
        for (TableEvent e : w.table(REM_COLUMNS)) {
            OID idx = e.getIndex();
            if (idx.size() < 3) continue;
            VariableBinding[] c = e.getColumns();

            Builder b = new Builder();
            b.localPortNum = idx.get(1);
            Integer chassisSub = intOf(c[0]);
            Integer portSub = intOf(c[2]);
            b.chassisIdSubtype = name(CHASSIS_SUBTYPES, chassisSub);
            b.chassisId = decodeId(chassisSub, octets(c[1]), 4, 5);
            b.portIdSubtype = name(PORT_SUBTYPES, portSub);
            b.portId = decodeId(portSub, octets(c[3]), 3, 4);
            b.portDescription = text(octets(c[4]));
            b.systemName = text(octets(c[5]));
            b.systemDescription = text(octets(c[6]));
            b.capabilitiesSupported = decodeCaps(octets(c[7]));
            b.capabilitiesEnabled = decodeCaps(octets(c[8]));

            resolveLocalPort(b, locPorts.get(b.localPortNum), ifs);
            byKey.put(key(idx), b);
        }

        // 4. Management addresses (parsed from the table index)
        if (!byKey.isEmpty()) {
            for (TableEvent e : w.table(REM_MAN_ADDR_IF_SUBTYPE)) {
                OID idx = e.getIndex();
                if (idx.size() < 5) continue;
                Builder b = byKey.get(key(idx));
                if (b == null) continue;
                int addrSubtype = idx.get(3);
                int declaredLen = idx.get(4);
                int[] raw = idx.getValue();
                // Spec says the length prefix is present; some agents omit it.
                int start = (idx.size() - 5 == declaredLen) ? 5 : 4;
                b.managementAddresses.add(formatAddress(addrSubtype, Arrays.copyOfRange(raw, start, raw.length)));
            }
        }

        List<LLDPNeighbor> result = new ArrayList<>(byKey.size());
        for (Builder b : byKey.values()) result.add(b.build());
        return result;
    }

    // ---- Per-call internals -----------------------------------------------------------

    private record LocalPort(Integer subtype, String portId, String portDesc) { }

    private record Interfaces(Map<Integer, String> name, Map<Integer, String> descr, Map<Integer, String> alias) {
        boolean exists(int ifIndex) {
            return name.containsKey(ifIndex) || descr.containsKey(ifIndex);
        }
    }

    /** Mutable accumulator used only inside a single discover() call. */
    private static final class Builder {
        int localPortNum;
        Integer localIfIndex;
        boolean localIfIndexGuessed;
        String localPortName, chassisIdSubtype, chassisId, portIdSubtype, portId;
        String portDescription, systemName, systemDescription;
        Set<String> capabilitiesSupported = Set.of();
        Set<String> capabilitiesEnabled = Set.of();
        final List<String> managementAddresses = new ArrayList<>();

        LLDPNeighbor build() {
            return new LLDPNeighbor(localPortNum, localIfIndex, localIfIndexGuessed, localPortName,
                    chassisIdSubtype, chassisId, portIdSubtype, portId, portDescription,
                    systemName, systemDescription, capabilitiesSupported, capabilitiesEnabled,
                    managementAddresses);
        }
    }

    /** Wraps the SNMP walking for one session/target pair. */
    private static final class Walker {
        private final Target<?> target;
        private final TableUtils tableUtils;

        Walker(Snmp snmp, Target<?> target, int maxRowsPerPdu) {
            this.target = target;
            int pduType = target.getVersion() == SnmpConstants.version1 ? PDU.GETNEXT : PDU.GETBULK;
            this.tableUtils = new TableUtils(snmp, new DefaultPDUFactory(pduType));
            this.tableUtils.setMaxNumRowsPerPDU(maxRowsPerPdu);
        }

        List<TableEvent> table(OID... columns) throws IOException {
            List<TableEvent> out = new ArrayList<>();
            for (TableEvent e : tableUtils.getTable(target, columns, null, null)) {
                if (e.isError()) {
                    if (e.getStatus() == TableEvent.STATUS_TIMEOUT) {
                        throw new IOException("SNMP timeout walking " + columns[0] + " on " + target.getAddress());
                    }
                    continue; // noSuchObject / not supported / partial -> treat as empty
                }
                out.add(e);
            }
            return out;
        }

        Map<Integer, String> column(OID col) throws IOException {
            Map<Integer, String> m = new HashMap<>();
            for (TableEvent e : table(col)) {
                String v = text(octets(e.getColumns()[0]));
                if (v != null) m.put(e.getIndex().get(0), v);
            }
            return m;
        }
    }

    // ---- Local port -> ifIndex mapping ------------------------------------------------

    private static void resolveLocalPort(Builder b, LocalPort loc, Interfaces ifs) {
        if (loc != null) {
            b.localPortName = loc.portId() != null ? loc.portId() : loc.portDesc();

            // Try exact name matches first: lldpLocPortId, then lldpLocPortDesc
            for (String candidate : new String[]{loc.portId(), loc.portDesc()}) {
                if (candidate == null || candidate.isEmpty()) continue;
                Integer hit = find(ifs.name(), candidate);
                if (hit == null) hit = find(ifs.descr(), candidate);
                if (hit == null && Integer.valueOf(1).equals(loc.subtype())) hit = find(ifs.alias(), candidate);
                if (hit != null) { b.localIfIndex = hit; return; }
            }
            // subtype "local" often carries the ifIndex as a number
            if (Integer.valueOf(7).equals(loc.subtype()) && loc.portId() != null && loc.portId().matches("\\d+")) {
                int i = Integer.parseInt(loc.portId());
                if (ifs.exists(i)) { b.localIfIndex = i; return; }
            }
        }
        // Fallback: many vendors use ifIndex as lldpLocPortNum, but it's not guaranteed.
        if (ifs.exists(b.localPortNum)) {
            b.localIfIndex = b.localPortNum;
            b.localIfIndexGuessed = true;
            if (b.localPortName == null) {
                b.localPortName = ifs.name().getOrDefault(b.localPortNum, ifs.descr().get(b.localPortNum));
            }
        }
    }

    private static Integer find(Map<Integer, String> map, String value) {
        for (Map.Entry<Integer, String> e : map.entrySet()) {
            if (value.equalsIgnoreCase(e.getValue())) return e.getKey();
        }
        return null;
    }

    // ---- Static helpers ---------------------------------------------------------------

    private static int[] concat(int[] prefix, int... suffix) {
        int[] r = Arrays.copyOf(prefix, prefix.length + suffix.length);
        System.arraycopy(suffix, 0, r, prefix.length, suffix.length);
        return r;
    }

    private static String key(OID idx) {
        return idx.get(0) + "." + idx.get(1) + "." + idx.get(2);
    }

    private static OctetString octets(VariableBinding vb) {
        return (vb != null && vb.getVariable() instanceof OctetString os) ? os : null;
    }

    private static Integer intOf(VariableBinding vb) {
        if (vb == null || vb.getVariable() instanceof Null) return null;
        try { return vb.getVariable().toInt(); } catch (UnsupportedOperationException ex) { return null; }
    }

    private static String name(String[] names, Integer v) {
        return (v != null && v > 0 && v < names.length) ? names[v] : String.valueOf(v);
    }

    private static String decodeId(Integer subtype, OctetString v, int macSubtype, int netSubtype) {
        if (v == null) return null;
        if (subtype != null && subtype == macSubtype && v.length() == 6) return v.toHexString(':');
        if (subtype != null && subtype == netSubtype) return decodeNetworkAddress(v);
        return text(v);
    }

    /** networkAddress subtype: first byte is IANA address family, then the address. */
    private static String decodeNetworkAddress(OctetString v) {
        byte[] b = v.getValue();
        try {
            if (b.length == 5 && b[0] == 1) return InetAddress.getByAddress(Arrays.copyOfRange(b, 1, 5)).getHostAddress();
            if (b.length == 17 && b[0] == 2) return InetAddress.getByAddress(Arrays.copyOfRange(b, 1, 17)).getHostAddress();
        } catch (UnknownHostException ignored) { }
        return v.toHexString(':');
    }

    private static String formatAddress(int subtype, int[] raw) {
        byte[] b = new byte[raw.length];
        for (int i = 0; i < raw.length; i++) b[i] = (byte) raw[i];
        try {
            if ((subtype == 1 && b.length == 4) || (subtype == 2 && b.length == 16)) {
                return InetAddress.getByAddress(b).getHostAddress();
            }
        } catch (UnknownHostException ignored) { }
        return new OctetString(b).toHexString(':');
    }

    /** SNMP BITS: bit 0 is the most significant bit of the first octet. */
    private static Set<String> decodeCaps(OctetString bits) {
        Set<String> caps = new LinkedHashSet<>();
        if (bits == null) return caps;
        for (int i = 0; i < CAPABILITIES.length; i++) {
            int byteIdx = i / 8;
            if (byteIdx >= bits.length()) break;
            if ((bits.get(byteIdx) & (0x80 >> (i % 8))) != 0) caps.add(CAPABILITIES[i]);
        }
        return caps;
    }

    /** Printable text if it looks like text, otherwise colon-separated hex. */
    private static String text(OctetString s) {
        if (s == null) return null;
        byte[] v = s.getValue();
        int len = v.length;
        while (len > 0 && v[len - 1] == 0) len--; // some agents null-terminate
        for (int i = 0; i < len; i++) {
            int c = v[i] & 0xff;
            if ((c < 0x20 && c != '\t' && c != '\r' && c != '\n') || c == 0x7f) return s.toHexString(':');
        }
        return new String(v, 0, len, StandardCharsets.UTF_8).trim();
    }
}